// Generated by scripts/sync-diagnostic-content.py from the Junior repo — do not edit by hand.
window.JUNIOR_DIAGNOSTIC_CONTENT = {
  "strategique": {
    "key": "diagnostic-strategique-v2",
    "title": "Diagnostic Stratégique",
    "scoreMax": 250,
    "maturityLevels": [
      {
        "min": 0,
        "max": 39,
        "label": "Désalignement critique",
        "description": "La vision, les priorités et l'exécution sont fragmentées. Les décisions reposent sur les individus, pas sur un cadre stratégique structuré."
      },
      {
        "min": 40,
        "max": 59,
        "label": "Alignement en développement",
        "description": "Certains éléments stratégiques existent mais ne sont pas intégrés. Les leaders peuvent exprimer des visions différentes selon le contexte."
      },
      {
        "min": 60,
        "max": 74,
        "label": "Alignement partiel",
        "description": "L'organisation a de bonnes intentions stratégiques et des indicateurs clairs, mais des écarts persistent entre la stratégie, l'exécution et l'alignement des équipes."
      },
      {
        "min": 75,
        "max": 89,
        "label": "Alignement fort",
        "description": "L'orientation stratégique et la gestion de la performance sont bien structurées. Quelques améliorations ciblées permettraient d'atteindre l'excellence."
      },
      {
        "min": 90,
        "max": 100,
        "label": "Alignement de classe mondiale",
        "description": "L'organisation intègre pleinement vision, mesure et exécution. La gouvernance et la communication sont parfaitement synchronisées."
      }
    ],
    "dimensions": [
      {
        "id": "D1",
        "title": "Orientation stratégique",
        "subtitle": "Vision · Positionnement · Objectifs stratégiques",
        "description": "Cette dimension évalue si votre organisation a défini un cap clair, ambitieux et partagé — et si ce cap guide activement les décisions.",
        "questions": [
          {
            "id": "Q1",
            "title": "La raison d'être",
            "text": "Est-ce que la formulation actuelle de votre raison d'être est centrée sur une transformation significative de votre marché, de vos clients ou de la société — ou est-elle principalement centrée sur des objectifs internes (croissance du chiffre d'affaires, marge, parts de marché) ?",
            "rationale": "Une organisation dont les leaders sont centrés sur des objectifs internes plutôt que sur une transformation externe risque la stagnation et la perte de pertinence face à l'évolution rapide des attentes clients."
          },
          {
            "id": "Q2",
            "title": "Le positionnement et la proposition de valeur",
            "text": "Est-ce que votre proposition de valeur est si claire et distinctive que vos leaders l'articulent tous de la même façon, et que vos clients la reconnaissent immédiatement comme différente de vos concurrents ?",
            "rationale": "Si chaque leader « vend » l'organisation différemment, le positionnement n'est pas ancré. C'est un travail fondamental avant tout effort de croissance ou d'expansion."
          },
          {
            "id": "Q3",
            "title": "Le modèle d'affaires",
            "text": "Est-ce que votre modèle d'affaires est documenté et compris par votre équipe de direction ? C'est-à-dire que tout le monde comprend comment vous créez, livrez et capturez de la valeur ?",
            "rationale": "Un modèle d'affaires non documenté crée des angles morts dans les décisions stratégiques. On ne peut pas optimiser ce qu'on n'a pas formalisé."
          },
          {
            "id": "Q4",
            "title": "L'analyse stratégique",
            "text": "Est-ce que votre organisation a une lecture claire et partagée de ses forces, faiblesses, opportunités et menaces — et est-ce que cette lecture influence activement vos décisions stratégiques ?",
            "rationale": "Une analyse stratégique qui n'est pas partagée et régulièrement mise à jour est un exercice académique. On cherche à savoir si l'analyse stratégique est vivante ou dormante dans l'organisation."
          },
          {
            "id": "Q5",
            "title": "La stratégie par perspective",
            "text": "Est-ce que votre stratégie est déclinée de façon cohérente dans chacune des grandes perspectives de votre organisation (financière, cliente, processus internes, équipes et apprentissage) — ou reste-t-elle surtout dans la tête du dirigeant ?",
            "rationale": "Une stratégie qui n'est pas cascadée par perspective reste une intention. Cette question révèle si la direction peut traduire la vision en priorités concrètes pour chaque fonction."
          },
          {
            "id": "Q6",
            "title": "Les objectifs et leur logique causale",
            "text": "Est-ce que vos objectifs stratégiques sont définis par perspective, et est-ce que les liens de cause à effet entre ces objectifs sont documentés — tout le monde comprend pourquoi atteindre l'objectif A mène à l'objectif B ?",
            "rationale": "Des objectifs sans liens causaux génèrent des efforts en silo. Quand une équipe ne comprend pas comment son objectif contribue à celui des autres, l'alignement est impossible."
          }
        ]
      },
      {
        "id": "D2",
        "title": "Cibles & mesure",
        "subtitle": "KPIs · Indicateurs de performance · Trajectoire chiffrée",
        "description": "Cette dimension évalue si votre organisation traduit sa stratégie en objectifs mesurables, indicateurs concrets et trajectoire dans le temps.",
        "questions": [
          {
            "id": "Q7",
            "title": "La qualité des indicateurs",
            "text": "Est-ce que vos indicateurs de performance incluent à la fois des indicateurs de résultat (ce qu'on a accompli), des indicateurs prédictifs (ce qui annonce les résultats à venir), et des garde-fous de qualité (ce qu'on ne doit pas sacrifier en visant les résultats) ?",
            "rationale": "Des organisations qui mesurent uniquement les résultats passés découvrent les problèmes trop tard pour réagir. Les indicateurs prédictifs et les garde-fous permettent d'intervenir avant que les résultats ne se dégradent."
          },
          {
            "id": "Q8",
            "title": "La rigueur SMART des objectifs",
            "text": "Est-ce que vos objectifs stratégiques sont formulés de façon suffisamment précise pour qu'on puisse évaluer sans ambiguïté si on les a atteints ou non — avec une cible chiffrée, un horizon temporel défini et un responsable nommé ?",
            "rationale": "Un objectif vague est un souhait. Un objectif SMART est un engagement. La distinction change radicalement la dynamique de responsabilisation dans l'équipe."
          },
          {
            "id": "Q9",
            "title": "L'alignement des indicateurs avec la stratégie",
            "text": "Est-ce que chacun de vos objectifs stratégiques est mesurable par un ou plusieurs indicateurs qui lui sont directement liés — ou certains objectifs restent-ils sans mesure concrète associée ?",
            "rationale": "Un objectif sans indicateur est une déclaration d'intention. L'alignement entre objectifs et indicateurs est ce qui transforme la stratégie en système de gestion de la performance."
          },
          {
            "id": "Q10",
            "title": "La cohérence de la trajectoire dans le temps",
            "text": "Est-ce que votre organisation a documenté une trajectoire temporelle cohérente entre son état actuel et ses objectifs à long terme — avec des jalons intermédiaires validés arithmétiquement (les résultats à court terme s'additionnent logiquement pour atteindre la vision à long terme) ?",
            "rationale": "Beaucoup d'organisations ont une vision ambitieuse et un plan annuel — mais l'écart entre les deux n'est pas structuré. Cette cohérence de trajectoire est ce qui distingue un plan crédible d'un exercice de planification."
          },
          {
            "id": "Q11",
            "title": "La North Star et le cap partagé",
            "text": "Est-ce que votre organisation a une métrique ou un indicateur principal — une North Star — qui cristallise l'essentiel de votre ambition et que tous les membres de l'équipe de direction peuvent citer spontanément ?",
            "rationale": "Quand tout le monde pilote vers la même étoile, les décisions quotidiennes s'alignent naturellement. Sans North Star partagée, chaque département optimise pour ses propres métriques au détriment de la cohérence globale."
          }
        ]
      },
      {
        "id": "D3",
        "title": "Alignement & exécution",
        "subtitle": "OKRs · Plans d'équipe · Cadences de gestion",
        "description": "Cette dimension évalue si votre stratégie descend concrètement jusqu'à chaque niveau de l'organisation, avec des cadences de pilotage qui transforment les intentions en résultats.",
        "questions": [
          {
            "id": "Q12",
            "title": "Les OKRs ou équivalents trimestriels",
            "text": "Est-ce que votre organisation utilise des engagements trimestriels structurés — objectifs qualitatifs inspirants et résultats chiffrés mesurables — pour traduire la stratégie annuelle en priorités d'exécution à court terme ?",
            "rationale": "Sans mécanisme trimestriel, la stratégie annuelle reste abstraite et l'urgence du quotidien prend le dessus. Les OKRs créent la cadence qui maintient le cap entre les révisions stratégiques."
          },
          {
            "id": "Q13",
            "title": "L'alignement des équipes à la stratégie",
            "text": "Est-ce que chaque département ou équipe peut expliquer clairement comment ses priorités du trimestre contribuent aux objectifs stratégiques de l'organisation — et est-ce que cet alignement est documenté et vérifié régulièrement ?",
            "rationale": "L'alignement déclaré et l'alignement réel sont souvent différents. Sans vérification structurée, les équipes optimisent pour leurs propres priorités locales plutôt que pour les objectifs collectifs."
          },
          {
            "id": "Q14",
            "title": "Les attentes de performance claires",
            "text": "Est-ce que les attentes de performance pour chaque rôle clé sont documentées, connues des titulaires et utilisées activement dans les conversations de développement et d'évaluation ?",
            "rationale": "Des attentes floues engendrent des évaluations subjectives, des frustrations et une rétention faible. La clarté des attentes est l'un des déterminants les plus importants de l'engagement et de la performance."
          },
          {
            "id": "Q15",
            "title": "Les tableaux de bord et la visibilité de la performance",
            "text": "Est-ce que vos leaders disposent d'un tableau de bord qui leur donne une vue claire et en temps quasi réel de la santé stratégique de l'organisation — statut des objectifs, indicateurs clés, signaux d'alerte — leur permettant de prendre des décisions informées rapidement ?",
            "rationale": "Un tableau de bord exécutif bien conçu réduit le temps de détection des problèmes et accélère les décisions correctives. Sans visibilité partagée, les équipes naviguent à l'intuition."
          },
          {
            "id": "Q16",
            "title": "La cadence de pilotage (réunions structurées)",
            "text": "Est-ce que votre organisation a des cadences de pilotage structurées et disciplinées à chaque niveau — revue hebdomadaire d'équipe, revue mensuelle de gestion, revue trimestrielle stratégique — où les décisions sont prises à partir des données, pas des opinions ?",
            "rationale": "La cadence de pilotage est le système circulatoire de la stratégie. Sans elle, les problèmes s'accumulent, les décisions tardent et les équipes se désynchronisent. La discipline de la cadence est ce qui rend l'amélioration continue possible."
          }
        ]
      },
      {
        "id": "D4",
        "title": "Maturité & capacités",
        "subtitle": "Maturité organisationnelle · Capacité d'exécution · Excellence opérationnelle",
        "description": "Cette dimension évalue si votre organisation a la maturité réelle pour exécuter la stratégie qu'elle s'est donnée — pas seulement l'intention, mais la capacité.",
        "questions": [
          {
            "id": "Q17",
            "title": "La maturité des processus",
            "text": "Est-ce que vos processus opérationnels clés sont documentés, standardisés et suivis avec discipline — ou reposent-ils principalement sur les habitudes et l'expérience individuelle des personnes en poste ?",
            "rationale": "Des processus non documentés créent une dépendance aux individus. Quand une personne clé part, le savoir-faire part avec elle. La standardisation des processus est la base de la scalabilité."
          },
          {
            "id": "Q18",
            "title": "La maturité des données et de la prise de décision",
            "text": "Est-ce que vos décisions importantes sont prises à partir de données fiables et structurées — ou reposent-elles surtout sur l'intuition, l'expérience individuelle ou des données incomplètes et difficiles à obtenir ?",
            "rationale": "Les organisations pilotées par les données prennent de meilleures décisions plus rapidement. La maturité des données n'est pas une question de technologie — c'est une question de discipline et de culture."
          },
          {
            "id": "Q19",
            "title": "La maturité de l'infrastructure technologique",
            "text": "Est-ce que votre infrastructure technologique — outils, systèmes, plateformes — supporte activement vos objectifs stratégiques, ou est-elle un frein à l'exécution que l'équipe doit constamment contourner ?",
            "rationale": "La technologie doit servir la stratégie, pas l'inverse. Une infrastructure inadaptée ralentit l'exécution, crée des silos de données et limite la capacité à scaler."
          },
          {
            "id": "Q20",
            "title": "La capacité au changement",
            "text": "Est-ce que votre organisation a démontré sa capacité à implanter des changements importants avec succès — ou est-ce que les initiatives de transformation ont tendance à s'essouffler avant d'atteindre leurs objectifs ?",
            "rationale": "La capacité au changement est un actif organisationnel. Les mandats de transformation échouent rarement par manque de bonnes idées — ils échouent par manque de capacité organisationnelle à les faire vivre."
          }
        ]
      },
      {
        "id": "D5",
        "title": "Priorisation & séquençage",
        "subtitle": "Priorisation stratégique · Roadmap · Allocation des ressources",
        "description": "Cette dimension évalue si votre organisation investit son temps et son capital aux bons endroits, au bon moment — avec une logique de priorisation défendable et une roadmap alignée sur sa vision.",
        "questions": [
          {
            "id": "Q21",
            "title": "La clarté de la vision comme ancre de priorisation",
            "text": "Est-ce que votre vision à court, moyen et long terme est suffisamment claire et partagée pour servir de critère de priorisation — quand il faut choisir entre deux projets, pouvez-vous trancher objectivement en référence à votre vision ?",
            "rationale": "Sans vision claire comme ancre, les décisions de priorisation deviennent politiques — on choisit les projets des personnes les plus influentes, pas les plus stratégiques."
          },
          {
            "id": "Q22",
            "title": "La connaissance du paysage concurrentiel",
            "text": "Est-ce que vous avez une lecture claire et récente de votre positionnement face à vos concurrents — leurs forces, leurs faiblesses, et les espaces stratégiques où vous avez un avantage réel ou potentiel ?",
            "rationale": "Une organisation qui ne connaît pas bien son paysage concurrentiel investit souvent dans des initiatives qui ne créent pas d'avantage différencié."
          },
          {
            "id": "Q23",
            "title": "La voix du client dans les décisions",
            "text": "Est-ce que les priorités de votre organisation sont influencées par une écoute structurée de vos clients — ce qu'ils aiment, ce dont ils ont besoin, ce qui leur manque, ce qu'ils éviteraient si possible ?",
            "rationale": "Les organisations qui priorisent sans écoute structurée du client finissent par construire ce qu'elles pensent bon plutôt que ce que le marché veut vraiment."
          },
          {
            "id": "Q24",
            "title": "L'analyse des coûts et bénéfices des initiatives",
            "text": "Est-ce que vos décisions d'investissement dans de nouvelles initiatives sont basées sur une analyse rigoureuse de l'effort requis, de l'impact attendu, de la portée et du niveau de confiance dans les hypothèses — ou plutôt sur l'enthousiasme et l'intuition ?",
            "rationale": "L'intuition est un point de départ, pas un mécanisme de priorisation. Comparer objectivement des initiatives très différentes sur une base commune est ce qui rend la roadmap défendable."
          },
          {
            "id": "Q25",
            "title": "La capacité et l'expertise disponibles",
            "text": "Est-ce que votre organisation prend en compte de façon réaliste ses capacités actuelles — ressources humaines, expertise disponible, bande passante des équipes — avant de s'engager dans de nouvelles initiatives stratégiques ?",
            "rationale": "Surestimer la capacité organisationnelle est l'une des causes les plus fréquentes d'échec des initiatives. Cette question force une évaluation honnête de ce que l'organisation peut réellement porter sans sacrifier l'exécution en cours."
          }
        ]
      }
    ]
  },
  "commercialisation": {
    "key": "diagnostic-commercialisation-v3",
    "title": "Diagnostic Commercialisation",
    "scoreMax": 300,
    "maturityLevels": [
      {
        "min": 0,
        "max": 39,
        "label": "Infrastructure absente",
        "description": "L'organisation vend principalement par instinct et relations personnelles. Aucune structure commerciale documentée. La croissance dépend entièrement des individus."
      },
      {
        "min": 40,
        "max": 59,
        "label": "Fondations en construction",
        "description": "Certains éléments commerciaux existent (ICP approximatif, offre définie) mais ne sont pas intégrés dans un système cohérent. Les résultats sont imprévisibles."
      },
      {
        "min": 60,
        "max": 74,
        "label": "Système partiel",
        "description": "L'organisation dispose d'une stratégie commerciale et de quelques outils, mais l'exécution est inégale. La croissance existe mais reste difficile à prévoir et à scaler."
      },
      {
        "min": 75,
        "max": 89,
        "label": "Système opérationnel",
        "description": "L'approche commerciale est structurée, mesurée et améliorée régulièrement. La croissance est prévisible. Quelques optimisations permettraient d'accélérer."
      },
      {
        "min": 90,
        "max": 100,
        "label": "Machine commerciale",
        "description": "L'organisation dispose d'un système commercial complet, aligné et performant. Elle transforme ses clients en actifs de croissance et scale avec discipline."
      }
    ],
    "dimensions": [
      {
        "id": "D1",
        "title": "Fondations commerciales",
        "subtitle": "ICP · Proposition de valeur · Positionnement concurrentiel",
        "description": "Cette dimension évalue si les bases de votre système commercial sont en place — à qui vous vendez, pourquoi vous choisir, et comment vous vous différenciez.",
        "questions": [
          {
            "id": "Q1",
            "title": "La clarté du profil client idéal (ICP)",
            "text": "Est-ce que votre organisation a défini de façon précise et documentée son profil de client idéal — le secteur, la taille, le rôle du décideur, les déclencheurs d'achat et les signaux d'alerte qui indiquent qu'un prospect n'est pas un bon fit ?",
            "rationale": "Un ICP flou force les équipes commerciales à pitcher à tout le monde et à convaincre personne. C'est la première source de cycles de vente longs et de taux de conversion faibles."
          },
          {
            "id": "Q2",
            "title": "La proposition de valeur différenciée",
            "text": "Est-ce que votre proposition de valeur est formulée en termes de résultats concrets pour le client — et est-ce qu'elle est suffisamment distinctive pour que vos clients comprennent immédiatement pourquoi vous et pas un compétiteur ?",
            "rationale": "Une proposition de valeur générique force à compétitionner sur le prix. La clarté et la différenciation sont les deux leviers qui permettent de justifier une valeur supérieure et de raccourcir le cycle de vente."
          },
          {
            "id": "Q3",
            "title": "La connaissance du paysage concurrentiel",
            "text": "Est-ce que votre équipe a une lecture claire et récente de vos compétiteurs directs et indirects — leurs forces, leurs faiblesses, leur positionnement — et est-ce que cette lecture influence activement vos décisions commerciales ?",
            "rationale": "Ignorer le paysage concurrentiel expose à se faire supplanter sans l'avoir vu venir. La connaissance concurrentielle est un avantage tactique direct dans chaque conversation de vente."
          },
          {
            "id": "Q4",
            "title": "La cohérence du message commercial",
            "text": "Est-ce que tous les membres de votre équipe commerciale articulent le même message — même problème adressé, même différenciation, même proposition de valeur — ou est-ce que le message varie selon la personne qui parle ?",
            "rationale": "Un message commercial incohérent crée de la confusion chez le prospect et dilue la crédibilité de l'organisation. L'alignement du message est un multiplicateur de performance commercial souvent sous-estimé."
          }
        ]
      },
      {
        "id": "D2",
        "title": "Connaissance du parcours client",
        "subtitle": "Customer Journey · Points de friction · Différenciation par étape",
        "description": "Cette dimension évalue si vous comprenez comment vos clients achètent — étape par étape — et si vous adaptez votre approche à chaque moment de leur parcours.",
        "questions": [
          {
            "id": "Q5",
            "title": "La cartographie du parcours client",
            "text": "Est-ce que votre organisation a documenté les étapes par lesquelles passe un client — de la prise de conscience jusqu'à l'achat et au-delà — et est-ce que cette cartographie est utilisée pour guider vos décisions commerciales et marketing ?",
            "rationale": "Sans cartographie du parcours, les efforts commerciaux s'appliquent aux mauvaises étapes. Savoir où le client en est change radicalement le message à livrer et le canal à utiliser."
          },
          {
            "id": "Q6",
            "title": "Les points de friction identifiés",
            "text": "Est-ce que vous savez où vos prospects décrochent dans le processus d'achat — à quelle étape les opportunités se perdent le plus souvent, et pourquoi — et est-ce que vous prenez des actions concrètes pour réduire ces frictions ?",
            "rationale": "La majorité des revenus perdus ne viennent pas d'un mauvais produit mais d'un parcours mal calibré. Identifier et éliminer les frictions est l'un des leviers les plus rapides pour améliorer les taux de conversion."
          },
          {
            "id": "Q7",
            "title": "La stratégie de différenciation par étape",
            "text": "Est-ce que votre approche commerciale s'adapte à l'étape où se trouve le prospect — contenu de sensibilisation pour ceux qui découvrent, arguments de comparaison pour ceux qui évaluent, preuves sociales pour ceux qui hésitent — ou utilisez-vous le même discours peu importe où en est le client ?",
            "rationale": "Un message adapté à l'étape du parcours convertit significativement mieux. La différenciation ne s'exprime pas seulement vs les compétiteurs — elle s'exprime aussi selon le moment où se trouve le client dans sa réflexion."
          }
        ]
      },
      {
        "id": "D3",
        "title": "Modèle économique et mise en marché",
        "subtitle": "Pricing · Stratégie GTM · Canaux d'acquisition",
        "description": "Cette dimension évalue si vos choix de prix, de canaux et de mise en marché sont structurés, documentés et économiquement viables.",
        "questions": [
          {
            "id": "Q8",
            "title": "La logique de fixation des prix",
            "text": "Est-ce que vos prix sont établis en fonction de la valeur perçue et des résultats que vous créez pour vos clients — ou sont-ils principalement basés sur vos coûts, sur ce que la compétition charge, ou sur ce que vous croyez que le marché peut accepter ?",
            "rationale": "La tarification basée sur la valeur est le levier le plus direct sur la rentabilité. Une organisation qui prix selon ses coûts laisse systématiquement de l'argent sur la table et se positionne comme une commodité plutôt qu'un partenaire stratégique."
          },
          {
            "id": "Q9",
            "title": "La stratégie GTM documentée",
            "text": "Est-ce que votre organisation dispose d'une stratégie de mise en marché documentée — canaux prioritaires, messages par segment, séquence d'activation, objectifs mesurables — ou est-ce que l'approche commerciale reste principalement dans la tête des personnes clés ?",
            "rationale": "Une stratégie GTM non documentée est fragile — elle dépend des individus, pas du système. La documenter permet de la tester, de l'améliorer et de la scaler sans tout recommencer à chaque changement d'équipe."
          },
          {
            "id": "Q10",
            "title": "La priorisation des canaux d'acquisition",
            "text": "Est-ce que vous avez clairement identifié et priorisé vos 1 à 2 canaux d'acquisition principaux — et est-ce que vos ressources (temps, budget, attention) sont concentrées sur ces canaux, ou sont-elles dispersées sur trop de fronts simultanément ?",
            "rationale": "Vouloir être partout à la fois est la stratégie commerciale la plus courante et la moins efficace. La concentration sur les canaux qui fonctionnent le mieux pour votre ICP spécifique est ce qui crée une croissance prévisible."
          },
          {
            "id": "Q11",
            "title": "Le mouvement commercial (séquence d'activation)",
            "text": "Est-ce que votre équipe suit une séquence commerciale structurée et reproductible — de la première interaction jusqu'à la signature — ou est-ce que chaque vendeur a sa propre façon de faire avec peu de cohérence dans l'approche ?",
            "rationale": "Un mouvement commercial reproductible est la différence entre une équipe de vente et un système de vente. La prévisibilité des revenus dépend directement de la discipline dans l'exécution de la séquence."
          }
        ]
      },
      {
        "id": "D4",
        "title": "Pipeline de vente",
        "subtitle": "Structure du cycle de vente · Taux de conversion · Prédictibilité",
        "description": "Cette dimension évalue si votre cycle de vente est structuré, mesurable et prévisible — ou s'il repose principalement sur l'intuition des vendeurs.",
        "questions": [
          {
            "id": "Q12",
            "title": "La structure du pipeline de vente",
            "text": "Est-ce que votre organisation dispose d'un pipeline de vente structuré avec des stages clairement définis, des critères de progression explicites entre chaque étape, et une probabilité de conversion associée à chaque stage — ou le cycle de vente reste-t-il informel et variable selon les individus ?",
            "rationale": "Un pipeline sans structure ne peut pas être piloté. Sans critères de progression explicites, les deals avancent sur la base de l'optimisme plutôt que sur des signaux concrets d'acheteur — ce qui rend le forecast impossible."
          },
          {
            "id": "Q13",
            "title": "La mesure des taux de conversion par stage",
            "text": "Est-ce que vous mesurez vos taux de conversion à chaque étape du cycle de vente — du premier contact jusqu'à la signature — et utilisez-vous ces données pour identifier où les opportunités se perdent et comment y remédier ?",
            "rationale": "Les taux de conversion par stage sont le système de diagnostic de votre machine commerciale. Un taux anormalement bas à une étape précise pointe vers un problème spécifique et traitable — un ICP mal défini, un message qui ne convainc pas, ou une proposition sans ROI clair."
          },
          {
            "id": "Q14",
            "title": "La fiabilité du forecast et la prédictibilité des revenus",
            "text": "Est-ce que vos prévisions de revenus sont basées sur des données structurées de votre pipeline — probabilités pondérées, stades validés, historique de conversion — ou reposent-elles principalement sur les estimations intuitives de vos vendeurs ?",
            "rationale": "Un forecast fiable change la nature des décisions commerciales — on peut investir avec confiance, embaucher au bon moment, et éviter les crises de liquidité. Sans forecast, l'organisation navigue à l'aveugle et prend des décisions réactives plutôt que proactives."
          }
        ]
      },
      {
        "id": "D5",
        "title": "Exécution et pilotage",
        "subtitle": "Tableau de pilotage · Métriques · Apprentissages terrain",
        "description": "Cette dimension évalue si votre exécution commerciale est visible, mesurée et apprenante — ou si elle se déroule dans l'ombre avec peu de données exploitables.",
        "questions": [
          {
            "id": "Q15",
            "title": "Le suivi des métriques commerciales",
            "text": "Est-ce que votre organisation mesure systématiquement ses métriques commerciales clés — leads générés, taux de conversion, durée du cycle de vente, coût d'acquisition, valeur des transactions — à une fréquence régulière et prévisible ?",
            "rationale": "Ce qu'on ne mesure pas, on ne peut pas améliorer. Les organisations qui pilotent avec des données prennent de meilleures décisions plus vite et évitent de perpétuer des approches qui ne fonctionnent pas."
          },
          {
            "id": "Q16",
            "title": "La discipline d'apprentissage terrain",
            "text": "Est-ce que votre équipe documente systématiquement ce qui fonctionne et ce qui ne fonctionne pas dans vos actions commerciales — et est-ce que ces apprentissages influencent activement vos décisions de la semaine ou du mois suivant ?",
            "rationale": "La plupart des équipes répètent les mêmes erreurs parce qu'elles n'ont pas de mécanisme pour capturer et utiliser leurs apprentissages. Un journal d'apprentissages terrain est ce qui transforme l'expérience en avantage compétitif durable."
          },
          {
            "id": "Q17",
            "title": "L'unité économique de base",
            "text": "Est-ce que vous connaissez précisément votre unité économique de base — valeur moyenne d'une transaction, coût d'acquisition d'un client, valeur vie client (LTV) — et est-ce que ces chiffres guident vos décisions d'investissement en marketing et en ventes ?",
            "rationale": "Sans connaître son unité économique, une organisation ne peut pas décider combien investir pour acquérir un client, ni évaluer si ses efforts commerciaux sont rentables. C'est le fondement de toute décision commerciale rationnelle."
          },
          {
            "id": "Q18",
            "title": "La cadence de revue commerciale",
            "text": "Est-ce que votre organisation a une cadence régulière et structurée de revue commerciale — hebdomadaire pour les actions, mensuelle pour les métriques, trimestrielle pour les hypothèses — où les décisions sont prises en fonction des données, pas des opinions ?",
            "rationale": "Une revue commerciale sans cadence devient une réunion de statut sans impact. La cadence crée l'obligation de décider, et la décision basée sur des données crée l'amélioration continue."
          }
        ]
      },
      {
        "id": "D6",
        "title": "Croissance par le client",
        "subtitle": "Évaluation des opportunités · Onboarding · Rétention · Partenariat",
        "description": "Cette dimension évalue si votre organisation transforme ses clients en actifs de croissance — en les livrant bien, en les fidélisant et en les mobilisant comme source de nouveaux revenus.",
        "questions": [
          {
            "id": "Q19",
            "title": "La qualification des opportunités",
            "text": "Est-ce que votre équipe applique une grille de qualification structurée pour évaluer chaque opportunité commerciale — fit avec l'ICP, problème réel et urgent, budget disponible, décideur identifié — ou est-ce que les opportunités sont poursuivies principalement sur la base de l'intuition ou de l'enthousiasme ?",
            "rationale": "Poursuivre les mauvaises opportunités est l'une des principales sources de gaspillage de ressources commerciales. Une grille de qualification disciplinée protège le temps de l'équipe et concentre l'énergie sur les deals qui ont le plus de chances de se conclure."
          },
          {
            "id": "Q20",
            "title": "La qualité de l'expérience d'onboarding",
            "text": "Est-ce que votre processus d'onboarding client est documenté, cohérent et conçu pour créer de la valeur rapidement — réduisant le temps entre la signature et le premier résultat concret perçu par le client ?",
            "rationale": "L'onboarding est le moment où le client décide inconsciemment s'il va devenir un ambassadeur ou un détracteur. Un onboarding structuré réduit le churn, accélère les référencements et augmente la valeur à vie du client."
          },
          {
            "id": "Q21",
            "title": "La transformation des clients en source de croissance",
            "text": "Est-ce que vos clients actuels contribuent activement à votre croissance — via des références, des témoignages, des renouvellements ou des expansions de mandats — ou est-ce que la relation s'arrête essentiellement à la livraison du mandat initial ?",
            "rationale": "Le client le plus facile à vendre est celui qui vous a déjà fait confiance. Les organisations qui systématisent la croissance par le client réduisent leur dépendance à l'acquisition constante de nouveaux prospects."
          }
        ]
      },
      {
        "id": "D7",
        "title": "Intelligence concurrentielle",
        "subtitle": "Présence numérique · Tactiques marketing · Stack technologique",
        "description": "Cette dimension évalue le niveau de connaissance active que votre organisation a du marketing et des tactiques commerciales de ses compétiteurs — au-delà de la simple connaissance de leur positionnement et de leur offre.",
        "questions": [
          {
            "id": "Q22",
            "title": "La présence numérique et le contenu des compétiteurs",
            "text": "Est-ce que vous avez une vue à jour de la présence numérique de vos compétiteurs — leur référencement organique, leur présence sur les réseaux sociaux, la fréquence et l'engagement de leur contenu — ou votre lecture du paysage est-elle surtout basée sur leurs sites web statiques ?",
            "rationale": "La présence numérique active d'un compétiteur est souvent le meilleur indicateur de ses intentions de croissance et des marchés qu'il cible activement. Ignorer cette dimension crée des angles morts stratégiques."
          },
          {
            "id": "Q23",
            "title": "Les tactiques d'acquisition payées des compétiteurs",
            "text": "Est-ce que vous savez quelles publicités payantes (Google Ads, LinkedIn, Meta) vos compétiteurs diffusent actuellement — les messages, les formats, les audiences ciblées — ou cette dimension de leur stratégie marketing vous est-elle largement inconnue ?",
            "rationale": "Les publicités payantes d'un compétiteur révèlent ses priorités de marché et ses arguments de vente actuels. Cette information est publique et accessible — ne pas la connaître, c'est naviguer à l'aveugle sur ce qui influence activement vos prospects."
          },
          {
            "id": "Q24",
            "title": "Les séquences de nurturing des compétiteurs",
            "text": "Est-ce que vous avez déjà testé les séquences de nurturing de vos compétiteurs — en vous inscrivant à leurs listes, en téléchargeant leur contenu ou en demandant une démo — pour comprendre comment ils cultivent leurs prospects dans le temps ?",
            "rationale": "Les séquences email sont l'un des signaux les plus riches sur la sophistication marketing d'un compétiteur. Savoir ce qu'ils disent à vos prospects communs — et dans quel ordre — est un avantage tactique direct en vente."
          },
          {
            "id": "Q25",
            "title": "La présence événementielle et institutionnelle des compétiteurs",
            "text": "Est-ce que vous savez dans quels événements, associations ou conférences vos compétiteurs sont actifs — et quel rôle ils y jouent (exposant, conférencier, commanditaire) — notamment dans les marchés que vous ciblez ?",
            "rationale": "La présence événementielle d'un compétiteur signale où il investit pour bâtir sa crédibilité et ses relations. Dans certains secteurs, la présence institutionnelle est aussi déterminante que la qualité du produit."
          },
          {
            "id": "Q26",
            "title": "Le stack technologique des compétiteurs",
            "text": "Est-ce que vous connaissez les outils (CRM, automatisation marketing, analytics) que vos principaux compétiteurs utilisent pour opérer leur système commercial et marketing — et ce que cela révèle sur leur niveau de sophistication et leurs investissements ?",
            "rationale": "Le stack technologique d'un compétiteur est un révélateur de maturité. Ces choix signalent les segments qu'ils adressent, les ressources qu'ils investissent et les processus qu'ils ont automatisés. C'est une information publique et facilement accessible."
          },
          {
            "id": "Q27",
            "title": "Le positionnement prix relatif des compétiteurs",
            "text": "Est-ce que vous avez une lecture claire et récente du positionnement prix de vos compétiteurs — premium, parité ou discount — et est-ce que cette lecture influence activement votre stratégie de prix et vos arguments de vente ?",
            "rationale": "Ignorer le positionnement prix de la compétition expose à des surprises en fin de cycle de vente. Connaître où vous vous positionnez relativement permet d'adapter votre argumentaire et de préparer vos équipes aux objections."
          }
        ]
      },
      {
        "id": "D8",
        "title": "Captation, Scoring & Activation",
        "subtitle": "Signaux d'intention · Qualification · Séquences d'activation",
        "description": "Cette dimension évalue si votre organisation a mis en place un système pour détecter les signaux commerciaux, qualifier ses prospects de façon structurée et déclencher des actions d'activation déterministes.",
        "questions": [
          {
            "id": "Q28",
            "title": "Les deux moteurs de demande",
            "text": "Est-ce que votre organisation distingue clairement, dans son allocation de ressources, les actions visant à créer de la demande (contenu, notoriété, présence de marque) des actions visant à capter la demande existante (signaux, scoring, activation) — ou est-ce que l'ensemble de vos efforts est traité comme un seul bloc sans cette distinction ?",
            "rationale": "À tout moment, environ 5 % de vos cibles sont en marché. Les 95 % restants le seront un jour. Une organisation qui n'investit que dans la captation s'épuise à pêcher dans un étang limité. Créer de la demande, c'est bâtir un pipeline futur avec chaque contenu et chaque prise de parole."
          },
          {
            "id": "Q29",
            "title": "Le scoring et la qualification structurée des prospects",
            "text": "Est-ce que votre organisation utilise un système structuré pour qualifier et prioriser ses prospects — basé sur le profil de l'entreprise (fit) et les signaux comportementaux observables (intent) — ou la décision de qui contacter en priorité repose-t-elle principalement sur l'intuition et l'expérience individuelle des vendeurs ?",
            "rationale": "Un système de scoring transforme la qualification d'un art individuel en processus organisationnel. Sans lui, les organisations investissent autant de temps sur un prospect mal qualifié que sur un compte idéal."
          },
          {
            "id": "Q30",
            "title": "Les règles de routing et les séquences d'activation",
            "text": "Est-ce que votre organisation a des règles documentées qui définissent quelle action commerciale déclencher selon le score et le signal d'un prospect — qui contacte, par quel canal, dans quel délai — ou est-ce que le passage d'un signal détecté à une action concrète reste informel et variable selon les individus ?",
            "rationale": "La vitesse et la précision de la réponse à un signal commercial sont souvent ce qui sépare un deal gagné d'une occasion ratée. Une règle de routing déterministe transforme une intention en avantage compétitif systématique."
          }
        ]
      }
    ]
  }
};
