#!/usr/bin/env python3
"""Regenerates diagnostic-questions/fr.js from the Junior repo's diagnostic
content, and checks that the hand-maintained English translation
(diagnostic-questions/en.js) still has exactly the same dimensions/questions.

    python3 scripts/sync-diagnostic-content.py [path/to/junior]

Sources (Junior repo): content/diagnostics/*.yaml for the questions, scoring
dimensions and maturity levels; content/prose/diagnostics/*.md for question
titles, dimension blurbs and maturity-level descriptions, which the YAML
doesn't carry. Deliberately never copies `reportInstructions` or `ctaText` —
those stay server-side. Needs PyYAML (`pip install pyyaml`).
"""
import json
import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
JUNIOR = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ROOT.parent / "junior")
OUT_DIR = ROOT / "diagnostic-questions"
GLOBAL = "JUNIOR_DIAGNOSTIC_CONTENT"


def build(key, prose_file):
    template = yaml.safe_load((JUNIOR / "content/diagnostics" / f"{key}.yaml").read_text("utf8"))
    prose = (JUNIOR / "content/prose/diagnostics" / prose_file).read_text("utf8")
    titles = {m[1]: m[2].strip() for m in re.finditer(r"^\*\*(Q\d+) — (.+?)\*\*\s*$", prose, re.M)}
    blurbs = {
        "D" + m[1]: m[2].strip()
        for m in re.finditer(r"^## DIMENSION (\d+) — .+\n(?:.*\n){0,3}?\*(Cette dimension[^*]+)\*", prose, re.M)
    }
    level_descs = {m[1].strip(): m[2].strip() for m in re.finditer(r"^\| \d+ – \d+ \| ([^|]+?) \| ([^|]+?) \|\s*$", prose, re.M)}
    questions = {q["id"]: q for q in template["questions"]}

    dimensions = []
    for dim in template["dimensions"]:
        if dim["id"] not in blurbs:
            sys.exit(f"{key}: no description found for {dim['id']} in {prose_file}")
        dim_questions = []
        for qid in dim["questionIds"]:
            if qid not in titles:
                sys.exit(f"{key}: no title found for {qid} in {prose_file}")
            q = questions[qid]
            dim_questions.append({
                "id": qid,
                "title": titles[qid],
                "text": q["text"].strip(),
                "rationale": (q.get("rationale") or "").strip(),
            })
        dimensions.append({
            "id": dim["id"],
            "title": dim["title"],
            "subtitle": dim["subtitle"],
            "description": blurbs[dim["id"]],
            "questions": dim_questions,
        })

    return {
        "key": key,
        "title": template["title"],
        "scoreMax": template["scoreMax"],
        "maturityLevels": [{**lvl, "description": level_descs.get(lvl["label"], "")} for lvl in template["maturityLevels"]],
        "dimensions": dimensions,
    }


def shape(content):
    return {
        part: [(d["id"], [q["id"] for q in d["questions"]]) for d in data["dimensions"]]
        + [("levels", [(l["min"], l["max"]) for l in data["maturityLevels"]])]
        for part, data in content.items()
    }


def write_js(path, content, header):
    body = json.dumps(content, ensure_ascii=False, indent=2)
    path.write_text(f"// {header}\nwindow.{GLOBAL} = {body};\n", "utf8")


def read_js(path):
    text = path.read_text("utf8")
    return json.loads(text[text.index("{"):text.rindex("}") + 1])


fr = {
    "strategique": build("diagnostic-strategique-v2", "diagnostic-strategique-v2.md"),
    "commercialisation": build("diagnostic-commercialisation-v3", "diagnostic-commercialisation-v3.md"),
}
write_js(OUT_DIR / "fr.js", fr, "Generated by scripts/sync-diagnostic-content.py from the Junior repo — do not edit by hand.")
print(f"wrote {OUT_DIR / 'fr.js'}")

en_path = OUT_DIR / "en.js"
if en_path.exists() and shape(read_js(en_path)) != shape(fr):
    sys.exit("en.js no longer matches fr.js's dimensions/questions/levels — update the English translation.")
print("en.js matches fr.js structure")
